### ISSUE TITLE
Importing `@starkware-industries/starkware-crypto-utils` returns an empty object

### ISSUE THREAD

**Issue by luccamordente** [starkware-libs/starkware-crypto-utils#19]
**Describe the bug**
I'm upgrading from 0.0.2 to 0.2.0.
Importing from `'@starkware-industries/starkware-crypto-utils'` returns an empty object.

**To Reproduce**
```js
const starkwareCrypto = require("@starkware-industries/starkware-crypto-utils");

console.log({ "starkwareCrypto": starkwareCrypto }); 
// => { starkwareCrypto: {} }

console.log({ "starkwareCypto.keyDerivation": starkwareCrypto.keyDerivation }); 
// => { 'starkwareCypto.keyDerivation': undefined }
```

[Here's a CodeSandbox](https://codesandbox.io/p/sandbox/immutable-framework-g8qh43?embed=1&file=%2Fpackage.json&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clonc4sz000073b6eqmkom8t7%2522%252C%2522sizes%2522%253A%255B46.878612716763%252C53.121387283237%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clonc4sz000033b6eajjfllvd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clonc4sz000053b6e4fph6se1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clonc4sz000063b6e2c6tdu5w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clonc4sz000033b6eajjfllvd%2522%253A%257B%2522id%2522%253A%2522clonc4sz000033b6eajjfllvd%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clonc5ed1007e3b6ertdn8v71%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522id%2522%253A%2522clonc5zl500nx3b6ezm64d4pg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clonc5zl500nx3b6ezm64d4pg%2522%257D%252C%2522clonc4sz000063b6e2c6tdu5w%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clonc4sz000063b6e2c6tdu5w%2522%257D%252C%2522clonc4sz000053b6e4fph6se1%2522%253A%257B%2522id%2522%253A%2522clonc4sz000053b6e4fph6se1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clonc4sz000043b6eupfvhtn4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clonc4sz000043b6eupfvhtn4%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior**
I should be able to do this without an error:
```js
const starkwareCrypto = require("@starkware-industries/starkware-crypto-utils");

const ethSignature =
  "0x21fbf0696d5e0aa2ef41a2b4ffb623bcaf070461d61cf7251c74161f82fec3a43" +
  "70854bc0a34b3ab487c1bc021cd318c734c51ae29374f2beb0e6f2dd49b4bf41c";

starkwareCrypto.keyDerivation.getPrivateKeyFromEthSignature(ethSignature);
// TypeError: Cannot read properties of undefined (reading 'getPrivateKeyFromEthSignature')
```

**Comment by RedaOps** [comment]
Might be because of https://github.com/starkware-libs/starkware-crypto-utils/commit/01e5c58b09b46bac6c4b832b4a8a8601f6075db0 since it only exports as an ESM module

@dan-ziv

**Comment by luccamordente** [comment]
Doesn't work with ESM `import` either: [CodeSandbox](https://codesandbox.io/p/sandbox/condescending-phoebe-4gh229?embed=1&file=%2Fpackage.json%3A1%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clonc4sz000073b6eqmkom8t7%2522%252C%2522sizes%2522%253A%255B63.13778142091948%252C36.86221857908052%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clonc4sz000033b6eajjfllvd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clonc4sz000053b6e4fph6se1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clonc4sz000063b6e2c6tdu5w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clonc4sz000033b6eajjfllvd%2522%253A%257B%2522id%2522%253A%2522clonc4sz000033b6eajjfllvd%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clonc5ed1007e3b6ertdn8v71%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522id%2522%253A%2522clonc5zl500nx3b6ezm64d4pg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clonc5zl500nx3b6ezm64d4pg%2522%257D%252C%2522clonc4sz000063b6e2c6tdu5w%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clonc4sz000063b6e2c6tdu5w%2522%257D%252C%2522clonc4sz000053b6e4fph6se1%2522%253A%257B%2522id%2522%253A%2522clonc4sz000053b6e4fph6se1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clonc4sz000043b6eupfvhtn4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clonc4sz000043b6eupfvhtn4%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A17.950558213716107%257D)
