### ISSUE TITLE
 wallet.

### ISSUE THREAD

**Issue by AnatoliyKonstantinov777** [starkware-libs/starkware-crypto-utils#2]
Hello! You have come up with a very unfortunate and bad system for accessing the wallet.
https://www.argent.xyz/faq/
I used your testnet wallet https://app.testnet.jediswap.xyz/
I spent about 1 month testing.
Today I turned on the computer and there is no access to the wallet.
Of course, I deleted the file a long time ago, but I have a password. But for some reason your wallet is not restored by password.
There is no such function, and requires the creation of a new wallet.
I uninstalled and installed a new wallet.
My old wallet address: 0x039f29f00b9df8cce5ca1db4568d22d23121090561b5c67e8def6067cf9cc822
What should I do to regain access to it???
I know the wallet address, I know the password.
https://www.argent.xyz/faq/
 
Sincerely, Anatoly Konstantinov.

**Comment by AnatoliyKonstantinov777** [comment]
7

**Comment by dan-ziv** [comment]
Hi @AnatoliyKonstantinov777 
This is not the ArgentX wallet repo.
Please submit your issue here:
https://github.com/argentlabs/argent-x
